apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: omplatform

resources:
  - namespace.yaml
  - infra-services.yaml
  - shared/
  - oms-trade/
  - oms-fulfillment/
  - oms-finance/
  - oms-marketing/
  - oms-risk-integration/
  - cart-service/
  - oms-channel-adapter/
  - igw/
  - egw/
  - seckill-service/
  - wms-service/
