apiVersion: v1
kind: Service
metadata:
  name: egw
  namespace: omplatform
  labels:
    app: egw
spec:
  selector:
    app: egw
  ports:
    - port: 8088
      targetPort: 8088
      name: http
  type: ClusterIP