apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: wms-service-config
    behavior: create
    literals:
      - SERVER_PORT=8082
      - SPRING_APPLICATION_NAME=wms-service
      - SERVER_SHUTDOWN=graceful
      - SPRING_LIFECYCLE_TIMEOUT-PER-SHUTDOWN-PHASE=30s
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=always
      - DUBBO_CONSUMER_RETRIES=2
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:6033/oms_wms?useSSL=false&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
