apiVersion: v1
kind: Service
metadata:
  name: oms-channel-adapter
  namespace: omplatform
  labels:
    app: oms-channel-adapter
spec:
  selector:
    app: oms-channel-adapter
  ports:
    - port: 8086
      targetPort: 8086
      name: http
  type: ClusterIP