apiVersion: v1
kind: Service
metadata:
  name: oms-trade
  namespace: omplatform
  labels:
    app: oms-trade
spec:
  selector:
    app: oms-trade
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP