apiVersion: v1
kind: Service
metadata:
  name: oms-fulfillment
  namespace: omplatform
  labels:
    app: oms-fulfillment
spec:
  selector:
    app: oms-fulfillment
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  type: ClusterIP