# OM Platform — Redis Master 配置
# 适用: Redis 7.2
# 端口: 6379

port 6379
daemonize no
bind 0.0.0.0
protected-mode yes
requirepass omplatform
masterauth omplatform

# 持久化
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfsync everysec

# 连接
maxclients 10000
timeout 0
tcp-keepalive 300

# 内存
maxmemory 2gb
maxmemory-policy allkeys-lru
