# OM Platform — Redis Replica 2 配置
# 端口: 6381

port 6381
daemonize no
bind 0.0.0.0
protected-mode yes
requirepass omplatform
masterauth omplatform
replicaof redis-master 6379
replica-serve-stale-data yes
replica-read-only yes
replica-priority 100
save ""
appendonly no
maxclients 10000
timeout 0
tcp-keepalive 300
maxmemory 2gb
maxmemory-policy allkeys-lru
