apiVersion: v1
kind: Service
metadata:
  name: oms-risk-integration
  namespace: omplatform
  labels:
    app: oms-risk-integration
spec:
  selector:
    app: oms-risk-integration
  ports:
    - port: 8084
      targetPort: 8084
      name: http
  type: ClusterIP